export interface Product {
  ID: string,
  Nombre: string,
  PrecioTotalAlCosto: string,
  Cantidad: string,
  PrecioUnitarioAlCosto: string,
  PrecioConEnvioUNITARIO: string,
  PrecioConEnvioTOTAL: string,
  PrecioSugerido: string,
  EscalaDePrecio: string,
  PrecioSegunPesoVolumen: string,
  MiPrecio: string,
  VentasAprox: string,
  Link: string,
  REAL: string,
  Vendidos: string,
  Disponible: string,
  SellRate: string,
  image: string,
  Discount: string
}

export interface ProductFormatted {
  ID: string,
  Nombre: string,
  PrecioTotalAlCosto: number,
  Cantidad: number,
  PrecioUnitarioAlCosto: number,
  PrecioConEnvioUNITARIO: number,
  PrecioConEnvioTOTAL: number,
  PrecioSugerido: number,
  EscalaDePrecio: string,
  PrecioSegunPesoVolumen: number,
  MiPrecio: number,
  VentasAprox: number,
  Link: string,
  REAL: number,
  Vendidos: number,
  Disponible: number,
  SellRate: number,
  image: string,
  Discount: number
}
